apiVersion: v1
kind: ResourceQuota
metadata:
  name: env-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.quota.requestsMemory }}
    limits.memory: {{ .Values.quota.limitsMemory }}
    pods: {{ .Values.quota.pods | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: env-defaults
  namespace: {{ .Release.Namespace }}
spec:
  limits:
    - type: Container
      defaultRequest:
        {{- toYaml .Values.limitRange.defaultRequest | nindent 8 }}
      default:
        {{- toYaml .Values.limitRange.default | nindent 8 }}
